version: '3.8'

services:
  app:
    build: .
    container_name: apolo-suporte
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data:
