version: '3.8'

services:
  app:
    build: .
    container_name: apolo-suporte
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:3000"
    restart: always
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: apolo-suporte-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env

volumes:
  postgres_data:
